// Package companion holds the wire contract between a paired phone and the
// Mora kernel: the JSON schemas for device, pairing, Today, context, capture,
// receipt and health, plus the async operation envelope (envelope.go).
//
// The package is deliberately a leaf. It contains types, bounds, a stable enum
// vocabulary, strict decoding and validation — no I/O, no clock, no vault, no
// HTTP. It imports only the standard library and must never import
// internal/mora, so the contract can be compiled into fixtures, tests and other
// packages without dragging the kernel behind it. TestPackageIsALeaf enforces
// that.
//
// # The envelope keys
//
// Every payload carries "schema" and "schema_version" merged into the object,
// matching the machine contract in docs/architecture/22-cli-contracts.md.
// Adding a field is MINOR; removing, renaming or retyping one requires a
// SchemaVersion bump and a new golden directory.
//
// # Strict inbound, tolerant outbound
//
// The kernel decodes everything a device sends with DisallowUnknownFields and
// rejects an unknown field, an unknown enum value, an oversize body or a
// malformed timestamp. A device decoding a kernel projection must do the
// opposite: ignore fields it does not know, because new ones will appear
// without a version bump. Both halves are proved by tests in fixtures_test.go.
//
// # Timestamps
//
// Every timestamp is RFC3339, UTC, second precision, "Z" suffix, no fractional
// part. That is narrower than RFC3339 on purpose: it is what Swift's
// ISO8601DateFormatter parses with its default options, so the Go and Swift
// decoders agree on the committed goldens without per-field date strategies.
package companion

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strings"
	"time"
)

// SchemaVersion is the MAJOR version every payload in this package carries. It
// moves only for a breaking change (a removed, renamed or retyped field).
const SchemaVersion = 1

// Published schema names. A name is the pinning identity of a payload: a
// consumer pins on the name plus SchemaVersion and nothing else.
const (
	SchemaDevice    = "mora.companion.device"
	SchemaPairing   = "mora.companion.pairing"
	SchemaPairingOK = "mora.companion.pairing.confirmation"
	SchemaToday     = "mora.companion.today"
	SchemaContext   = "mora.companion.context"
	SchemaContextRq = "mora.companion.context.request"
	SchemaCapture   = "mora.companion.capture"
	SchemaReceipt   = "mora.companion.receipt"
	SchemaHealth    = "mora.companion.health"
	SchemaOperation = "mora.companion.operation"
)

// Byte and count bounds. Every bound is enforced by Validate or by Unmarshal,
// never left to the caller: an unbounded field is how a phone turns a projection
// into a denial of service and how a capture turns a log line into a leak.
const (
	// MaxCaptureBytes bounds a whole capture request. The text inside it is
	// bounded separately by MaxCaptureTextBytes.
	MaxCaptureBytes     = 24 << 10
	MaxCaptureTextBytes = 16 << 10
	// MaxRequestBytes bounds any other inbound request body.
	MaxRequestBytes = 64 << 10
	// MaxProjectionBytes bounds any outbound projection (Today, context,
	// health, receipt, device, pairing).
	MaxProjectionBytes = 4 << 20
	// MaxOperationBytes bounds the async operation envelope. It is small
	// because the envelope carries no user text — only a reference to it.
	MaxOperationBytes = 4 << 10

	MaxIDBytes              = 64
	MaxIdempotencyKeyBytes  = 128
	MaxLabelBytes           = 64
	MaxScopeBytes           = 128
	MaxQueryBytes           = 1 << 10
	MaxTitleBytes           = 200
	MaxBodyBytes            = 2 << 10
	MaxSnippetBytes         = 512
	MaxSourceKeyBytes       = 64
	MaxPublicKeyBytes       = 128
	MaxSynthesisPromptBytes = 8 << 10
	MaxGapBytes             = 200
	MaxDeepLinkBytes        = 512

	MaxTodayItems       = 3
	MaxEvidencePerItem  = 5
	MaxContextEvidence  = 32
	MaxCitations        = 32
	MaxGaps             = 16
	MaxFreshnessSources = 32
)

// Identifier prefixes. An identifier is "<prefix>_<opaque>": the opaque part is
// generated by the kernel and is not part of this contract, so no consumer may
// parse anything out of it.
const (
	PrefixDevice    = "dev_"
	PrefixRequest   = "req_"
	PrefixReceipt   = "rcp_"
	PrefixMemory    = "mem_"
	PrefixExecution = "exe_"
)

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

// Error codes. The vocabulary is stable: a caller maps a code to a
// RejectReason on a receipt, and the phone renders the reason.
const (
	CodeUnknownField   = "unknown_field"
	CodeMalformed      = "malformed"
	CodeTooLarge       = "too_large"
	CodeMissingField   = "missing_field"
	CodeInvalidEnum    = "invalid_enum"
	CodeInvalidValue   = "invalid_value"
	CodeTooManyItems   = "too_many_items"
	CodeSchemaMismatch = "schema_mismatch"
	CodeInvalidState   = "invalid_state"
)

// Error is the single error type this package returns. Field names the JSON
// path where that is known, so a rejection receipt can say what was wrong
// without echoing the value back into a log.
type Error struct {
	Code    string
	Field   string
	Message string
}

func (e *Error) Error() string {
	if e.Field == "" {
		return e.Code + ": " + e.Message
	}
	return e.Code + " at " + e.Field + ": " + e.Message
}

func errf(code, field, format string, args ...any) *Error {
	return &Error{Code: code, Field: field, Message: fmt.Sprintf(format, args...)}
}

// ---------------------------------------------------------------------------
// Enum vocabulary
// ---------------------------------------------------------------------------

// Lane names who executes an operation and under which governance. The kernel
// assigns it; a device may request one, but a request is never an
// authorization.
type Lane string

const (
	// LaneMemory is executed by the Mac that owns the vault: governed writes
	// and grounded reads.
	LaneMemory Lane = "memory"
	// LaneResearch is executed asynchronously off the Mac. It never writes
	// the vault directly; it returns a result the Mac files later.
	LaneResearch Lane = "research"
)

// Intent is the purpose the device declared. It is provenance and UI copy, and
// it is never used for routing — routing reads Lane and OperationKind, which
// only the kernel sets.
type Intent string

const (
	IntentRemember    Intent = "remember"
	IntentAsk         Intent = "ask"
	IntentInvestigate Intent = "investigate"
)

// ReceiptState is the terminal state of a governed write.
type ReceiptState string

const (
	// ReceiptAccepted means the kernel took the capture and staged it for
	// local approval. Nothing is in the vault yet.
	ReceiptAccepted ReceiptState = "accepted"
	// ReceiptApplied means the memory exists in the vault. Only this state
	// permits a device to say "saved".
	ReceiptApplied ReceiptState = "applied"
	// ReceiptRejected means the capture will never be applied. It always
	// carries a Reason.
	ReceiptRejected ReceiptState = "rejected"
)

// RejectReason is why a capture was rejected. Rejections are receipts, never
// drops: every capture gets exactly one terminal receipt.
type RejectReason string

const (
	ReasonPolicy              RejectReason = "policy"
	ReasonUnknownDevice       RejectReason = "unknown_device"
	ReasonRevokedDevice       RejectReason = "revoked_device"
	ReasonTooLarge            RejectReason = "too_large"
	ReasonMalformed           RejectReason = "malformed"
	ReasonUnsupportedLane     RejectReason = "unsupported_lane"
	ReasonIdempotencyConflict RejectReason = "idempotency_conflict"
	ReasonUnavailable         RejectReason = "unavailable"
	ReasonInternal            RejectReason = "internal"
)

// WritePolicy mirrors the kernel's mcp_write_policy vocabulary. readonly
// rejects a capture, propose accepts it for local approval, open applies it.
type WritePolicy string

const (
	PolicyOpen     WritePolicy = "open"
	PolicyPropose  WritePolicy = "propose"
	PolicyReadonly WritePolicy = "readonly"
)

// ContextMode selects which grounded retrieval builds a context bundle.
type ContextMode string

const (
	ModeThink       ContextMode = "think"
	ModeSearch      ContextMode = "search"
	ModeMeetingPrep ContextMode = "meeting_prep"
)

// HealthState is the kernel's overall honesty signal.
type HealthState string

const (
	HealthHealthy   HealthState = "healthy"
	HealthDegraded  HealthState = "degraded"
	HealthUnhealthy HealthState = "unhealthy"
)

// FreshnessState mirrors internal/health's constants exactly. The vocabulary is
// copied rather than imported so this package stays a leaf; a divergence is a
// bug in whichever side moved.
type FreshnessState string

const (
	FreshnessFresh  FreshnessState = "fresh"
	FreshnessStale  FreshnessState = "stale"
	FreshnessFailed FreshnessState = "failed"
	FreshnessNever  FreshnessState = "never"
)

// DeviceState is a paired device's lifecycle.
type DeviceState string

const (
	DevicePending DeviceState = "pending"
	DeviceActive  DeviceState = "active"
	DeviceRevoked DeviceState = "revoked"
)

// Platform is the coarse device family. It is deliberately coarse: a model name
// would be a fingerprint.
type Platform string

const (
	PlatformIOS   Platform = "ios"
	PlatformMacOS Platform = "macos"
	PlatformOther Platform = "other"
)

// SourceErrorCode is the typed reason a source is not fresh. It is a code and
// never the connector's prose: an error string from a mail or message connector
// can carry an address, a subject line, or a filename, and a freshness row
// travels inside the content-free operation envelope. A frozen vocabulary is
// what keeps that envelope content-free by construction rather than by review.
type SourceErrorCode string

const (
	ErrAuthExpired        SourceErrorCode = "auth_expired"
	ErrPermissionDenied   SourceErrorCode = "permission_denied"
	ErrNetworkUnavailable SourceErrorCode = "network_unavailable"
	ErrRateLimited        SourceErrorCode = "rate_limited"
	ErrSourceUnavailable  SourceErrorCode = "source_unavailable"
	ErrNotConfigured      SourceErrorCode = "not_configured"
	ErrInternal           SourceErrorCode = "internal"
)

// PayloadMediaType is the only media type v1 carries.
const PayloadMediaType = "text/plain; charset=utf-8"

// TodayItemKind classifies a Today item.
type TodayItemKind string

const (
	ItemNeedsAttention TodayItemKind = "needs_attention"
	ItemChanged        TodayItemKind = "changed"
	ItemCommitment     TodayItemKind = "commitment"
)

// vocabulary lists every published enum value by JSON field family.
//
// It is unexported and reached only through VocabularyFor, which returns a
// copy. An exported map would be writable by any package in the process, and a
// vocabulary a caller can edit is not a stable enum: a test or a plugin could
// widen it and every Validate in this package would start accepting a value the
// contract never published.
var vocabulary = map[string][]string{
	"lane":              {string(LaneMemory), string(LaneResearch)},
	"intent":            {string(IntentRemember), string(IntentAsk), string(IntentInvestigate)},
	"kind":              {string(KindCapture), string(KindAsk), string(KindResearch)},
	"operation_state":   {string(StateCaptured), string(StateTriaged), string(StateLeased), string(StateRunning), string(StateDone), string(StateNeedsInput), string(StateFailed)},
	"receipt_state":     {string(ReceiptAccepted), string(ReceiptApplied), string(ReceiptRejected)},
	"reject_reason":     {string(ReasonPolicy), string(ReasonUnknownDevice), string(ReasonRevokedDevice), string(ReasonTooLarge), string(ReasonMalformed), string(ReasonUnsupportedLane), string(ReasonIdempotencyConflict), string(ReasonUnavailable), string(ReasonInternal)},
	"write_policy":      {string(PolicyOpen), string(PolicyPropose), string(PolicyReadonly)},
	"context_mode":      {string(ModeThink), string(ModeSearch), string(ModeMeetingPrep)},
	"health_state":      {string(HealthHealthy), string(HealthDegraded), string(HealthUnhealthy)},
	"freshness_state":   {string(FreshnessFresh), string(FreshnessStale), string(FreshnessFailed), string(FreshnessNever)},
	"device_state":      {string(DevicePending), string(DeviceActive), string(DeviceRevoked)},
	"platform":          {string(PlatformIOS), string(PlatformMacOS), string(PlatformOther)},
	"today_item_kind":   {string(ItemNeedsAttention), string(ItemChanged), string(ItemCommitment)},
	"origin":            {OriginCompanion, OriginCLI, OriginMCP},
	"media_type":        {PayloadMediaType},
	"source_error_code": {string(ErrAuthExpired), string(ErrPermissionDenied), string(ErrNetworkUnavailable), string(ErrRateLimited), string(ErrSourceUnavailable), string(ErrNotConfigured), string(ErrInternal)},
}

// VocabularyFamilies returns every published enum family, sorted.
func VocabularyFamilies() []string {
	out := make([]string, 0, len(vocabulary))
	for family := range vocabulary {
		out = append(out, family)
	}
	sort.Strings(out)
	return out
}

// VocabularyFor returns the published values of one enum family. The returned
// slice is a copy: the contract's vocabulary is not writable from outside this
// package.
func VocabularyFor(family string) []string {
	out := make([]string, len(vocabulary[family]))
	copy(out, vocabulary[family])
	return out
}

func inVocabulary(family, value, field string) error {
	for _, v := range vocabulary[family] {
		if v == value {
			return nil
		}
	}
	if value == "" {
		return errf(CodeMissingField, field, "%s is required", family)
	}
	return errf(CodeInvalidEnum, field, "not a published %s value", family)
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

// Header is the two-key envelope every payload merges in. It is embedded, so it
// marshals flat and first.
type Header struct {
	Schema        string `json:"schema"`
	SchemaVersion int    `json:"schema_version"`
}

func newHeader(name string) Header {
	return Header{Schema: name, SchemaVersion: SchemaVersion}
}

func (h Header) validate(name string) error {
	if h.Schema != name {
		return errf(CodeSchemaMismatch, "schema", "want %s", name)
	}
	if h.SchemaVersion != SchemaVersion {
		return errf(CodeSchemaMismatch, "schema_version", "want %d", SchemaVersion)
	}
	return nil
}

// ---------------------------------------------------------------------------
// Scalar validation
// ---------------------------------------------------------------------------

// validateTimestamp enforces RFC3339, UTC, second precision. See the package
// doc for why the format is narrower than RFC3339 itself.
func validateTimestamp(field, s string) error {
	if s == "" {
		return errf(CodeMissingField, field, "timestamp is required")
	}
	if !strings.HasSuffix(s, "Z") {
		return errf(CodeInvalidValue, field, "timestamp must be UTC and end in Z")
	}
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return errf(CodeInvalidValue, field, "timestamp is not RFC3339")
	}
	if t.UTC().Format(time.RFC3339) != s {
		return errf(CodeInvalidValue, field, "timestamp must have second precision and no fractional part")
	}
	return nil
}

func validateOptionalTimestamp(field, s string) error {
	if s == "" {
		return nil
	}
	return validateTimestamp(field, s)
}

// opaqueRunes reports whether s is limited to the opaque-token character set.
// Restricting it is what keeps a device from smuggling prose through an
// identifier into the content-free operation envelope.
func opaqueRunes(s string) bool {
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case r == '_' || r == '-' || r == '.' || r == ':':
		default:
			return false
		}
	}
	return true
}

func validateID(field, prefix, s string) error {
	if s == "" {
		return errf(CodeMissingField, field, "identifier is required")
	}
	if len(s) > MaxIDBytes {
		return errf(CodeTooLarge, field, "identifier exceeds %d bytes", MaxIDBytes)
	}
	if !strings.HasPrefix(s, prefix) || len(s) == len(prefix) {
		return errf(CodeInvalidValue, field, "identifier must start with %q and carry an opaque suffix", prefix)
	}
	if !opaqueRunes(s) {
		return errf(CodeInvalidValue, field, "identifier carries characters outside [A-Za-z0-9_.:-]")
	}
	return nil
}

func validateOptionalID(field, prefix, s string) error {
	if s == "" {
		return nil
	}
	return validateID(field, prefix, s)
}

func validateText(field, s string, max int, required bool) error {
	if s == "" {
		if required {
			return errf(CodeMissingField, field, "field is required")
		}
		return nil
	}
	if len(s) > max {
		return errf(CodeTooLarge, field, "exceeds %d bytes", max)
	}
	return nil
}

func validateCount(field string, n, max int) error {
	if n > max {
		return errf(CodeTooManyItems, field, "at most %d entries", max)
	}
	return nil
}

// validateFingerprint accepts only "sha256:" plus 64 lowercase hex digits.
func validateFingerprint(field, s string) error {
	const want = "sha256:"
	if s == "" {
		return errf(CodeMissingField, field, "fingerprint is required")
	}
	if !strings.HasPrefix(s, want) || len(s) != len(want)+64 {
		return errf(CodeInvalidValue, field, "fingerprint must be sha256:<64 hex>")
	}
	for _, r := range s[len(want):] {
		if r >= '0' && r <= '9' || r >= 'a' && r <= 'f' {
			continue
		}
		return errf(CodeInvalidValue, field, "fingerprint digest must be lowercase hex")
	}
	return nil
}

func validateOptionalFingerprint(field, s string) error {
	if s == "" {
		return nil
	}
	return validateFingerprint(field, s)
}

// validateScope accepts "personal" or "project:<name>". A device may not invent
// any other scope, and it may never name a source.
func validateScope(field, s string) error {
	if s == "" {
		return errf(CodeMissingField, field, "scope is required")
	}
	if len(s) > MaxScopeBytes {
		return errf(CodeTooLarge, field, "exceeds %d bytes", MaxScopeBytes)
	}
	if s == "personal" {
		return nil
	}
	name, ok := strings.CutPrefix(s, "project:")
	if !ok || name == "" || !opaqueRunes(name) {
		return errf(CodeInvalidValue, field, `scope must be "personal" or "project:<name>"`)
	}
	return nil
}

func validateIdempotencyKey(field, s string) error {
	if s == "" {
		return errf(CodeMissingField, field, "idempotency key is required")
	}
	if len(s) > MaxIdempotencyKeyBytes {
		return errf(CodeTooLarge, field, "exceeds %d bytes", MaxIdempotencyKeyBytes)
	}
	if !opaqueRunes(s) {
		return errf(CodeInvalidValue, field, "idempotency key carries characters outside [A-Za-z0-9_.:-]")
	}
	return nil
}

// ---------------------------------------------------------------------------
// Decoding
// ---------------------------------------------------------------------------

// Payload is implemented by every schema in this package.
type Payload interface {
	// SchemaName is the published name the payload must carry.
	SchemaName() string
	// ByteLimit is the largest encoded form the kernel will accept.
	ByteLimit() int
	// Validate enforces every bound, enum and cross-field rule.
	Validate() error
}

// Unmarshal decodes data into v with unknown fields rejected, enforces v's byte
// limit, and validates. It is the only decode path the kernel uses on anything
// a device sent.
func Unmarshal(data []byte, v Payload) error {
	if limit := v.ByteLimit(); limit > 0 && len(data) > limit {
		return errf(CodeTooLarge, "", "payload is %d bytes, limit is %d", len(data), limit)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(v); err != nil {
		if strings.Contains(err.Error(), "unknown field") {
			return errf(CodeUnknownField, "", "%s", err.Error())
		}
		return errf(CodeMalformed, "", "%s", err.Error())
	}
	if dec.More() {
		return errf(CodeMalformed, "", "trailing data after the JSON document")
	}
	return v.Validate()
}

// Marshal encodes a validated payload in the golden form: two-space indent and
// a trailing newline, so a committed fixture and a live response are the same
// bytes.
func Marshal(v Payload) ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return nil, err
	}
	b = append(b, '\n')
	// The bound is enforced on the way out as well as on the way in. Checking
	// it only on decode would leave a producer free to emit an operation
	// envelope past 4 KiB or a projection past 4 MiB, and the peer that
	// rejected it would be the only one to find out.
	if limit := v.ByteLimit(); limit > 0 && len(b) > limit {
		return nil, errf(CodeTooLarge, "", "encoded payload is %d bytes, limit is %d", len(b), limit)
	}
	return b, nil
}

// Fingerprint returns the payload fingerprint for a capture's text. It is the
// published derivation: SHA-256 over the exact UTF-8 bytes the device sent,
// rendered lowercase with a "sha256:" prefix. A device computes it, the kernel
// recomputes it, and a mismatch on a repeated idempotency key is
// ReasonIdempotencyConflict.
func Fingerprint(text string) string {
	sum := sha256.Sum256([]byte(text))
	return "sha256:" + hex.EncodeToString(sum[:])
}

// ---------------------------------------------------------------------------
// Freshness and health
// ---------------------------------------------------------------------------

// SourceFreshness is one connector's honesty row. AgeSeconds is -1 when the
// source has never succeeded.
type SourceFreshness struct {
	Key           string         `json:"key"`
	State         FreshnessState `json:"state"`
	AgeSeconds    int64          `json:"age_seconds"`
	LastSuccessAt string         `json:"last_success_at,omitempty"`
	// ErrorCode is the typed companion to a failure, drawn from the frozen
	// source_error_code vocabulary. It is never the connector's prose.
	ErrorCode SourceErrorCode `json:"error_code,omitempty"`
}

func (f SourceFreshness) validate(field string) error {
	if err := validateSourceKey(field+".key", f.Key); err != nil {
		return err
	}
	if err := inVocabulary("freshness_state", string(f.State), field+".state"); err != nil {
		return err
	}
	if f.AgeSeconds < -1 {
		return errf(CodeInvalidValue, field+".age_seconds", "age is -1 (never) or a non-negative count")
	}
	if err := validateOptionalTimestamp(field+".last_success_at", f.LastSuccessAt); err != nil {
		return err
	}
	// A freshness row is the product's honesty signal, so its three fields
	// have to agree. A "never" row that reports an age, or a "fresh" row with
	// no last success, is a row a client would render as a confident claim
	// nothing supports.
	switch f.State {
	case FreshnessNever:
		if f.LastSuccessAt != "" {
			return errf(CodeInvalidState, field+".last_success_at", "a never-successful source has no last success")
		}
		if f.AgeSeconds != -1 {
			return errf(CodeInvalidState, field+".age_seconds", "a never-successful source has age -1")
		}
	case FreshnessFresh, FreshnessStale:
		if f.LastSuccessAt == "" {
			return errf(CodeMissingField, field+".last_success_at", "a %s source succeeded at some point and says when", f.State)
		}
		if f.AgeSeconds < 0 {
			return errf(CodeInvalidState, field+".age_seconds", "a %s source has a non-negative age", f.State)
		}
	}
	if f.ErrorCode == "" {
		return nil
	}
	return inVocabulary("source_error_code", string(f.ErrorCode), field+".error_code")
}

// validateSourceKey bounds a connector key. It is unbounded nowhere: a
// freshness row rides inside the 4 KiB operation envelope, so a key with no
// ceiling is a way to push content through it.
func validateSourceKey(field, key string) error {
	if key == "" {
		return errf(CodeMissingField, field, "source key is required")
	}
	if len(key) > MaxSourceKeyBytes {
		return errf(CodeTooLarge, field, "exceeds %d bytes", MaxSourceKeyBytes)
	}
	if !opaqueRunes(key) {
		return errf(CodeInvalidValue, field, "source key carries characters outside [A-Za-z0-9_.:-]")
	}
	return nil
}

func validateFreshness(field string, rows []SourceFreshness) error {
	if err := validateCount(field, len(rows), MaxFreshnessSources); err != nil {
		return err
	}
	for i, r := range rows {
		if err := r.validate(fmt.Sprintf("%s[%d]", field, i)); err != nil {
			return err
		}
	}
	return nil
}

// IndexHealth is the vault index's own state, separate from connector
// freshness: a fresh connector with a stale index still lies to the reader.
type IndexHealth struct {
	State    HealthState `json:"state"`
	Memories int         `json:"memories"`
	BuiltAt  string      `json:"built_at,omitempty"`
}

// HealthProjection is GET /v1/companion/health.
type HealthProjection struct {
	Header
	GeneratedAt string            `json:"generated_at"`
	State       HealthState       `json:"state"`
	Policy      WritePolicy       `json:"policy"`
	Index       IndexHealth       `json:"index"`
	Sources     []SourceFreshness `json:"sources"`
}

// NewHealthProjection returns a projection with its envelope filled in.
func NewHealthProjection() HealthProjection {
	return HealthProjection{Header: newHeader(SchemaHealth), Sources: []SourceFreshness{}}
}

func (h *HealthProjection) SchemaName() string { return SchemaHealth }
func (h *HealthProjection) ByteLimit() int     { return MaxProjectionBytes }

func (h *HealthProjection) Validate() error {
	if err := h.validate(SchemaHealth); err != nil {
		return err
	}
	if err := validateTimestamp("generated_at", h.GeneratedAt); err != nil {
		return err
	}
	if err := inVocabulary("health_state", string(h.State), "state"); err != nil {
		return err
	}
	if err := inVocabulary("write_policy", string(h.Policy), "policy"); err != nil {
		return err
	}
	if err := inVocabulary("health_state", string(h.Index.State), "index.state"); err != nil {
		return err
	}
	if h.Index.Memories < 0 {
		return errf(CodeInvalidValue, "index.memories", "count cannot be negative")
	}
	if err := validateOptionalTimestamp("index.built_at", h.Index.BuiltAt); err != nil {
		return err
	}
	if h.Sources == nil {
		return errf(CodeMissingField, "sources", "an empty collection is [], never null")
	}
	return validateFreshness("sources", h.Sources)
}

// ---------------------------------------------------------------------------
// Evidence and citations
// ---------------------------------------------------------------------------

// Evidence is one retrieved record behind a projection. Snippet is bounded
// prose from the vault; it is the only free text a projection carries and it is
// what makes a claim checkable.
type Evidence struct {
	MemoryID   string `json:"memory_id"`
	Source     string `json:"source"`
	OccurredAt string `json:"occurred_at,omitempty"`
	Snippet    string `json:"snippet,omitempty"`
	DeepLink   string `json:"deep_link,omitempty"`
}

func (e Evidence) validate(field string) error {
	if err := validateID(field+".memory_id", PrefixMemory, e.MemoryID); err != nil {
		return err
	}
	if err := validateSourceKey(field+".source", e.Source); err != nil {
		return err
	}
	if err := validateOptionalTimestamp(field+".occurred_at", e.OccurredAt); err != nil {
		return err
	}
	if err := validateText(field+".snippet", e.Snippet, MaxSnippetBytes, false); err != nil {
		return err
	}
	return validateText(field+".deep_link", e.DeepLink, MaxDeepLinkBytes, false)
}

func validateEvidence(field string, rows []Evidence, max int) error {
	if rows == nil {
		return errf(CodeMissingField, field, "an empty collection is [], never null")
	}
	if err := validateCount(field, len(rows), max); err != nil {
		return err
	}
	for i, r := range rows {
		if err := r.validate(fmt.Sprintf("%s[%d]", field, i)); err != nil {
			return err
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Today
// ---------------------------------------------------------------------------

// TodayItem is one of at most MaxTodayItems things the phone shows. Every item
// carries its own evidence: a claim without evidence is not shippable.
type TodayItem struct {
	ID       string        `json:"id"`
	Kind     TodayItemKind `json:"kind"`
	Title    string        `json:"title"`
	Body     string        `json:"body,omitempty"`
	Evidence []Evidence    `json:"evidence"`
}

// TodayProjection is GET /v1/companion/today.
type TodayProjection struct {
	Header
	GeneratedAt string            `json:"generated_at"`
	Health      HealthSummary     `json:"health"`
	Items       []TodayItem       `json:"items"`
	Freshness   []SourceFreshness `json:"freshness"`
	// Truncated is true when the kernel had more than MaxTodayItems items to
	// show. The phone must render it: three of three is a different claim
	// from three of nine.
	Truncated bool `json:"truncated"`
}

// HealthSummary is the compact strip Today carries so no projection can be
// shown without saying how healthy its inputs were.
type HealthSummary struct {
	State  HealthState `json:"state"`
	Policy WritePolicy `json:"policy"`
}

// NewTodayProjection returns a projection with its envelope and empty
// collections filled in.
func NewTodayProjection() TodayProjection {
	return TodayProjection{
		Header:    newHeader(SchemaToday),
		Items:     []TodayItem{},
		Freshness: []SourceFreshness{},
	}
}

func (t *TodayProjection) SchemaName() string { return SchemaToday }
func (t *TodayProjection) ByteLimit() int     { return MaxProjectionBytes }

func (t *TodayProjection) Validate() error {
	if err := t.validate(SchemaToday); err != nil {
		return err
	}
	if err := validateTimestamp("generated_at", t.GeneratedAt); err != nil {
		return err
	}
	if err := inVocabulary("health_state", string(t.Health.State), "health.state"); err != nil {
		return err
	}
	if err := inVocabulary("write_policy", string(t.Health.Policy), "health.policy"); err != nil {
		return err
	}
	if t.Items == nil {
		return errf(CodeMissingField, "items", "an empty collection is [], never null")
	}
	if err := validateCount("items", len(t.Items), MaxTodayItems); err != nil {
		return err
	}
	for i, item := range t.Items {
		field := fmt.Sprintf("items[%d]", i)
		if err := validateText(field+".id", item.ID, MaxIDBytes, true); err != nil {
			return err
		}
		if !opaqueRunes(item.ID) {
			return errf(CodeInvalidValue, field+".id", "identifier carries characters outside [A-Za-z0-9_.:-]")
		}
		if err := inVocabulary("today_item_kind", string(item.Kind), field+".kind"); err != nil {
			return err
		}
		if err := validateText(field+".title", item.Title, MaxTitleBytes, true); err != nil {
			return err
		}
		if err := validateText(field+".body", item.Body, MaxBodyBytes, false); err != nil {
			return err
		}
		if err := validateEvidence(field+".evidence", item.Evidence, MaxEvidencePerItem); err != nil {
			return err
		}
		if len(item.Evidence) == 0 {
			return errf(CodeMissingField, field+".evidence", "every Today item carries at least one evidence row")
		}
	}
	if t.Freshness == nil {
		return errf(CodeMissingField, "freshness", "an empty collection is [], never null")
	}
	return validateFreshness("freshness", t.Freshness)
}

// ---------------------------------------------------------------------------
// Context bundle
// ---------------------------------------------------------------------------

// ContextRequest is POST /v1/companion/context. A device chooses a mode and a
// query; it cannot choose a source, a tool, or a budget.
type ContextRequest struct {
	Header
	Mode  ContextMode `json:"mode"`
	Query string      `json:"query"`
	Scope string      `json:"scope,omitempty"`
}

// NewContextRequest returns a request with its envelope filled in.
func NewContextRequest() ContextRequest {
	return ContextRequest{Header: newHeader(SchemaContextRq)}
}

func (c *ContextRequest) SchemaName() string { return SchemaContextRq }
func (c *ContextRequest) ByteLimit() int     { return MaxRequestBytes }

func (c *ContextRequest) Validate() error {
	if err := c.validate(SchemaContextRq); err != nil {
		return err
	}
	if err := inVocabulary("context_mode", string(c.Mode), "mode"); err != nil {
		return err
	}
	if err := validateText("query", c.Query, MaxQueryBytes, true); err != nil {
		return err
	}
	if c.Scope == "" {
		return nil
	}
	return validateScope("scope", c.Scope)
}

// ContextBundle is the answer to a ContextRequest. It is evidence, citations,
// gaps and a synthesis prompt — never a model-generated answer. The shell runs
// the model; the kernel supplies the grounding and says what it does not know.
type ContextBundle struct {
	Header
	GeneratedAt string      `json:"generated_at"`
	Mode        ContextMode `json:"mode"`
	Query       string      `json:"query"`
	Evidence    []Evidence  `json:"evidence"`
	// Gaps names what the vault does not know about this query. An empty
	// gaps list is a claim, so it is never omitted.
	Gaps            []string          `json:"gaps"`
	Freshness       []SourceFreshness `json:"freshness"`
	SynthesisPrompt string            `json:"synthesis_prompt"`
	Health          HealthSummary     `json:"health"`
}

// NewContextBundle returns a bundle with its envelope and empty collections
// filled in.
func NewContextBundle() ContextBundle {
	return ContextBundle{
		Header:    newHeader(SchemaContext),
		Evidence:  []Evidence{},
		Gaps:      []string{},
		Freshness: []SourceFreshness{},
	}
}

func (c *ContextBundle) SchemaName() string { return SchemaContext }
func (c *ContextBundle) ByteLimit() int     { return MaxProjectionBytes }

func (c *ContextBundle) Validate() error {
	if err := c.validate(SchemaContext); err != nil {
		return err
	}
	if err := validateTimestamp("generated_at", c.GeneratedAt); err != nil {
		return err
	}
	if err := inVocabulary("context_mode", string(c.Mode), "mode"); err != nil {
		return err
	}
	if err := validateText("query", c.Query, MaxQueryBytes, true); err != nil {
		return err
	}
	if err := validateEvidence("evidence", c.Evidence, MaxContextEvidence); err != nil {
		return err
	}
	if c.Gaps == nil {
		return errf(CodeMissingField, "gaps", "an empty collection is [], never null")
	}
	if err := validateCount("gaps", len(c.Gaps), MaxGaps); err != nil {
		return err
	}
	for i, g := range c.Gaps {
		if err := validateText(fmt.Sprintf("gaps[%d]", i), g, MaxGapBytes, true); err != nil {
			return err
		}
	}
	if c.Freshness == nil {
		return errf(CodeMissingField, "freshness", "an empty collection is [], never null")
	}
	if err := validateFreshness("freshness", c.Freshness); err != nil {
		return err
	}
	if err := validateText("synthesis_prompt", c.SynthesisPrompt, MaxSynthesisPromptBytes, true); err != nil {
		return err
	}
	if err := inVocabulary("health_state", string(c.Health.State), "health.state"); err != nil {
		return err
	}
	return inVocabulary("write_policy", string(c.Health.Policy), "health.policy")
}

// ---------------------------------------------------------------------------
// Capture
// ---------------------------------------------------------------------------

// Capture is POST /v1/companion/captures.
//
// Text is verbatim user text: a device never rewrites it, and the kernel stamps
// the source, so no device can claim a capture came from somewhere else.
// RequestedLane and Intent are what the device asked for; the kernel decides
// what actually runs and stamps the executed lane on the Operation.
type Capture struct {
	Header
	IdempotencyKey string `json:"idempotency_key"`
	DeviceID       string `json:"device_id"`
	CapturedAt     string `json:"captured_at"`
	RequestedLane  Lane   `json:"requested_lane"`
	Intent         Intent `json:"intent"`
	Scope          string `json:"scope"`
	Text           string `json:"text"`
	// PayloadFingerprint is sha256 over Text as the device sent it. It is what
	// makes "same key, same payload" answerable without storing the text
	// twice, and it is what turns "same key, different payload" into
	// ReasonIdempotencyConflict instead of a silent overwrite.
	PayloadFingerprint string `json:"payload_fingerprint"`
}

// NewCapture returns a capture with its envelope filled in.
func NewCapture() Capture { return Capture{Header: newHeader(SchemaCapture)} }

func (c *Capture) SchemaName() string { return SchemaCapture }
func (c *Capture) ByteLimit() int     { return MaxCaptureBytes }

func (c *Capture) Validate() error {
	if err := c.validate(SchemaCapture); err != nil {
		return err
	}
	if err := validateIdempotencyKey("idempotency_key", c.IdempotencyKey); err != nil {
		return err
	}
	if err := validateID("device_id", PrefixDevice, c.DeviceID); err != nil {
		return err
	}
	if err := validateTimestamp("captured_at", c.CapturedAt); err != nil {
		return err
	}
	if err := inVocabulary("lane", string(c.RequestedLane), "requested_lane"); err != nil {
		return err
	}
	if err := inVocabulary("intent", string(c.Intent), "intent"); err != nil {
		return err
	}
	if err := validateScope("scope", c.Scope); err != nil {
		return err
	}
	if err := validateText("text", c.Text, MaxCaptureTextBytes, true); err != nil {
		return err
	}
	if err := validateFingerprint("payload_fingerprint", c.PayloadFingerprint); err != nil {
		return err
	}
	// Syntax is not enough. The fingerprint is the idempotency identity: the
	// kernel answers "same key, same payload?" with it, so a fingerprint that
	// does not cover this text would let two different captures share one
	// identity and let the second silently take the first's receipt.
	if want := Fingerprint(c.Text); c.PayloadFingerprint != want {
		return errf(CodeInvalidValue, "payload_fingerprint", "fingerprint does not cover the capture text")
	}
	return ValidateRouting(c.RequestedLane, c.Intent)
}

// ValidateRouting enforces the published lane-and-intent matrix. An intent the
// lane cannot serve is rejected at the boundary rather than routed somewhere
// surprising.
func ValidateRouting(lane Lane, intent Intent) error {
	switch lane {
	case LaneMemory:
		if intent == IntentRemember || intent == IntentAsk {
			return nil
		}
	case LaneResearch:
		if intent == IntentInvestigate {
			return nil
		}
	}
	return errf(CodeInvalidState, "intent", "intent %q is not served by lane %q", intent, lane)
}

// ---------------------------------------------------------------------------
// Receipt
// ---------------------------------------------------------------------------

// Receipt is the terminal record for one capture, and the only thing that lets
// a phone say "saved". It is returned by POST /v1/companion/captures and listed
// by GET /v1/companion/receipts.
//
// A receipt carries the async job state machine in Operation when the capture
// was routed to a lane that does not settle in the request. That block is the
// seam to the agent spine (graph decision D6): the phone learns the job state
// and nothing about which worker or model produced it.
type Receipt struct {
	Header
	ReceiptID          string       `json:"receipt_id"`
	RequestID          string       `json:"request_id"`
	IdempotencyKey     string       `json:"idempotency_key"`
	DeviceID           string       `json:"device_id"`
	State              ReceiptState `json:"state"`
	Reason             RejectReason `json:"reason,omitempty"`
	MemoryID           string       `json:"memory_id,omitempty"`
	PayloadFingerprint string       `json:"payload_fingerprint"`
	Policy             WritePolicy  `json:"policy"`
	ReceivedAt         string       `json:"received_at"`
	SettledAt          string       `json:"settled_at,omitempty"`
	// Operation is present when the capture opened an async operation.
	Operation *OperationStatus `json:"operation,omitempty"`
}

// OperationStatus is the job-state slice of an Operation that a receipt
// carries. It is a projection of envelope.go's Operation, not a second source
// of truth.
type OperationStatus struct {
	RequestID string         `json:"request_id"`
	Lane      Lane           `json:"lane"`
	Kind      OperationKind  `json:"kind"`
	State     OperationState `json:"state"`
	UpdatedAt string         `json:"updated_at"`
	Attempts  int            `json:"attempts"`
}

// NewReceipt returns a receipt with its envelope filled in.
func NewReceipt() Receipt { return Receipt{Header: newHeader(SchemaReceipt)} }

func (r *Receipt) SchemaName() string { return SchemaReceipt }
func (r *Receipt) ByteLimit() int     { return MaxProjectionBytes }

func (r *Receipt) Validate() error {
	if err := r.validate(SchemaReceipt); err != nil {
		return err
	}
	if err := validateID("receipt_id", PrefixReceipt, r.ReceiptID); err != nil {
		return err
	}
	if err := validateID("request_id", PrefixRequest, r.RequestID); err != nil {
		return err
	}
	if err := validateIdempotencyKey("idempotency_key", r.IdempotencyKey); err != nil {
		return err
	}
	if err := validateID("device_id", PrefixDevice, r.DeviceID); err != nil {
		return err
	}
	if err := inVocabulary("receipt_state", string(r.State), "state"); err != nil {
		return err
	}
	if err := inVocabulary("write_policy", string(r.Policy), "policy"); err != nil {
		return err
	}
	if err := validateFingerprint("payload_fingerprint", r.PayloadFingerprint); err != nil {
		return err
	}
	if err := validateTimestamp("received_at", r.ReceivedAt); err != nil {
		return err
	}
	if err := validateOptionalTimestamp("settled_at", r.SettledAt); err != nil {
		return err
	}
	if err := validateOptionalID("memory_id", PrefixMemory, r.MemoryID); err != nil {
		return err
	}
	if r.Reason != "" {
		if err := inVocabulary("reject_reason", string(r.Reason), "reason"); err != nil {
			return err
		}
	}
	switch r.State {
	case ReceiptApplied:
		// The whole point of the receipt: applied is a claim that the vault
		// holds the memory, so it cannot be made without naming it.
		if r.MemoryID == "" {
			return errf(CodeInvalidState, "memory_id", "an applied receipt names the memory it created")
		}
		if r.SettledAt == "" {
			return errf(CodeInvalidState, "settled_at", "an applied receipt is settled")
		}
		if r.Reason != "" {
			return errf(CodeInvalidState, "reason", "an applied receipt has no rejection reason")
		}
	case ReceiptRejected:
		if r.Reason == "" {
			return errf(CodeMissingField, "reason", "a rejected receipt names its reason")
		}
		if r.MemoryID != "" {
			return errf(CodeInvalidState, "memory_id", "a rejected receipt created no memory")
		}
		if r.SettledAt == "" {
			return errf(CodeInvalidState, "settled_at", "a rejected receipt is settled")
		}
	case ReceiptAccepted:
		if r.MemoryID != "" {
			return errf(CodeInvalidState, "memory_id", "an accepted receipt has not published a memory yet")
		}
		if r.Reason != "" {
			return errf(CodeInvalidState, "reason", "an accepted receipt has no rejection reason")
		}
	}
	if err := validatePolicyOutcome(r.State, r.Reason, r.Policy); err != nil {
		return err
	}
	if r.Operation == nil {
		return nil
	}
	op := r.Operation
	if op.RequestID != r.RequestID {
		return errf(CodeInvalidState, "operation.request_id", "operation belongs to a different request")
	}
	if err := validateID("operation.request_id", PrefixRequest, op.RequestID); err != nil {
		return err
	}
	if err := inVocabulary("lane", string(op.Lane), "operation.lane"); err != nil {
		return err
	}
	if err := inVocabulary("kind", string(op.Kind), "operation.kind"); err != nil {
		return err
	}
	if err := inVocabulary("operation_state", string(op.State), "operation.state"); err != nil {
		return err
	}
	if err := validateTimestamp("operation.updated_at", op.UpdatedAt); err != nil {
		return err
	}
	if op.Attempts < 0 {
		return errf(CodeInvalidValue, "operation.attempts", "count cannot be negative")
	}
	return nil
}

// validatePolicyOutcome binds a receipt's state to the write policy that
// produced it, so a receipt cannot describe an outcome the policy could not
// have reached.
//
// The binding applies to the policy-determined outcomes — the ones where the
// policy alone decided what happened, which is when the receipt carries no
// reason or carries ReasonPolicy:
//
//	readonly -> rejected    propose -> accepted    open -> applied
//
// Every other rejection reason (unknown_device, too_large, idempotency_conflict
// and the rest) can occur under any policy, and those receipts are required to
// be rejected and are not bound further. Binding them to a policy as well would
// make an oversize capture unrepresentable under `open`, which is a real case
// N21 has to return.
func validatePolicyOutcome(state ReceiptState, reason RejectReason, policy WritePolicy) error {
	if reason != "" && reason != ReasonPolicy {
		if state != ReceiptRejected {
			return errf(CodeInvalidState, "state", "reason %q can only produce a rejected receipt", reason)
		}
		return nil
	}
	want := map[WritePolicy]ReceiptState{
		PolicyReadonly: ReceiptRejected,
		PolicyPropose:  ReceiptAccepted,
		PolicyOpen:     ReceiptApplied,
	}[policy]
	if state != want {
		return errf(CodeInvalidState, "state", "the %s policy produces a %s receipt, not %s", policy, want, state)
	}
	return nil
}

// ---------------------------------------------------------------------------
// Device and pairing
// ---------------------------------------------------------------------------

// Device is one paired phone as the kernel records it.
//
// It carries no bearer token. TokenFingerprint is sha256 over the token so a
// device list, a log line and a support screenshot can identify a credential
// without carrying one.
type Device struct {
	Header
	DeviceID         string      `json:"device_id"`
	Label            string      `json:"label"`
	Platform         Platform    `json:"platform"`
	State            DeviceState `json:"state"`
	TokenFingerprint string      `json:"token_fingerprint,omitempty"`
	CreatedAt        string      `json:"created_at"`
	LastSeenAt       string      `json:"last_seen_at,omitempty"`
	RevokedAt        string      `json:"revoked_at,omitempty"`
}

// NewDevice returns a device record with its envelope filled in.
func NewDevice() Device { return Device{Header: newHeader(SchemaDevice)} }

func (d *Device) SchemaName() string { return SchemaDevice }
func (d *Device) ByteLimit() int     { return MaxProjectionBytes }

func (d *Device) Validate() error {
	if err := d.validate(SchemaDevice); err != nil {
		return err
	}
	if err := validateID("device_id", PrefixDevice, d.DeviceID); err != nil {
		return err
	}
	if err := validateText("label", d.Label, MaxLabelBytes, true); err != nil {
		return err
	}
	if err := inVocabulary("platform", string(d.Platform), "platform"); err != nil {
		return err
	}
	if err := inVocabulary("device_state", string(d.State), "state"); err != nil {
		return err
	}
	if err := validateOptionalFingerprint("token_fingerprint", d.TokenFingerprint); err != nil {
		return err
	}
	if err := validateTimestamp("created_at", d.CreatedAt); err != nil {
		return err
	}
	if err := validateOptionalTimestamp("last_seen_at", d.LastSeenAt); err != nil {
		return err
	}
	if err := validateOptionalTimestamp("revoked_at", d.RevokedAt); err != nil {
		return err
	}
	switch d.State {
	case DeviceRevoked:
		if d.RevokedAt == "" {
			return errf(CodeInvalidState, "revoked_at", "a revoked device records when it was revoked")
		}
	case DevicePending, DeviceActive:
		if d.RevokedAt != "" {
			return errf(CodeInvalidState, "revoked_at", "a live device has no revocation time")
		}
	}
	if d.State == DevicePending && d.TokenFingerprint != "" {
		return errf(CodeInvalidState, "token_fingerprint", "a pending device has no credential yet")
	}
	// An active device is one the listener will authenticate, so it must
	// identify the credential it authenticates with. A revoked device may have
	// none: revocation deletes it.
	if d.State == DeviceActive && d.TokenFingerprint == "" {
		return errf(CodeMissingField, "token_fingerprint", "an active device names its credential by fingerprint")
	}
	return nil
}

// PairingPayload is what `mora companion pair` prints as a QR code.
//
// PairingCode is a one-time secret with a short expiry. This schema fixes only
// the envelope around it: the code's own format, and the format of the bearer
// token it is exchanged for, are a human decision gate and are opaque here.
// Never log this payload — call Redacted first.
type PairingPayload struct {
	Header
	DeviceID    string `json:"device_id"`
	Endpoint    string `json:"endpoint"`
	PairingCode string `json:"pairing_code"`
	ExpiresAt   string `json:"expires_at"`
	// HostFingerprint pins the Mac the phone is pairing with, so a pairing
	// code replayed against another host is visible to the human comparing
	// two printed fingerprints.
	HostFingerprint string `json:"host_fingerprint"`
}

// NewPairingPayload returns a pairing payload with its envelope filled in.
func NewPairingPayload() PairingPayload {
	return PairingPayload{Header: newHeader(SchemaPairing)}
}

func (p *PairingPayload) SchemaName() string { return SchemaPairing }
func (p *PairingPayload) ByteLimit() int     { return MaxProjectionBytes }

// Redacted returns a copy with the one-time code masked, for any path that
// prints, logs or reports a pairing payload.
func (p PairingPayload) Redacted() PairingPayload {
	if p.PairingCode != "" {
		p.PairingCode = "[redacted]"
	}
	return p
}

func (p *PairingPayload) Validate() error {
	if err := p.validate(SchemaPairing); err != nil {
		return err
	}
	if err := validateID("device_id", PrefixDevice, p.DeviceID); err != nil {
		return err
	}
	if err := validateText("endpoint", p.Endpoint, MaxDeepLinkBytes, true); err != nil {
		return err
	}
	if err := validateEndpoint("endpoint", p.Endpoint); err != nil {
		return err
	}
	if err := validateText("pairing_code", p.PairingCode, MaxIdempotencyKeyBytes, true); err != nil {
		return err
	}
	if err := validateTimestamp("expires_at", p.ExpiresAt); err != nil {
		return err
	}
	return validateFingerprint("host_fingerprint", p.HostFingerprint)
}

// validateEndpoint accepts https, or cleartext http only to a real loopback
// host.
//
// A prefix match is not good enough here and the difference is exploitable:
// "http://127.0.0.1:@evil.example/" starts with "http://127.0.0.1:" and points
// at evil.example, because everything before the "@" is userinfo. The URL is
// parsed, the host is compared, and any userinfo at all is refused — a pairing
// endpoint has no business carrying credentials in its authority.
func validateEndpoint(field, raw string) error {
	if err := validateText(field, raw, MaxDeepLinkBytes, true); err != nil {
		return err
	}
	u, err := url.Parse(raw)
	if err != nil {
		return errf(CodeInvalidValue, field, "endpoint is not a URL")
	}
	if u.User != nil {
		return errf(CodeInvalidValue, field, "endpoint must not carry userinfo")
	}
	switch u.Scheme {
	case "https":
		if u.Hostname() == "" {
			return errf(CodeInvalidValue, field, "endpoint has no host")
		}
		return nil
	case "http":
		switch u.Hostname() {
		case "127.0.0.1", "::1", "localhost":
			return nil
		}
		return errf(CodeInvalidValue, field, "cleartext is allowed only to a loopback host")
	}
	return errf(CodeInvalidValue, field, "endpoint scheme must be https, or http to loopback")
}

// validatePublicKey accepts "<alg>:<base64 of 32 bytes>" for the two key types
// a paired device presents: an ed25519 signing key and an X25519 agreement key.
// Both are 32 bytes, so a typed check here rejects a truncated, re-encoded, or
// entirely made-up key at the boundary instead of at first use.
func validatePublicKey(field, raw string) error {
	if err := validateText(field, raw, MaxPublicKeyBytes, true); err != nil {
		return err
	}
	alg, encoded, ok := strings.Cut(raw, ":")
	if !ok {
		return errf(CodeInvalidValue, field, "public key must be <alg>:<base64>")
	}
	switch alg {
	case "ed25519", "x25519":
	default:
		return errf(CodeInvalidEnum, field, "public key algorithm must be ed25519 or x25519")
	}
	key, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return errf(CodeInvalidValue, field, "public key is not standard base64")
	}
	if len(key) != 32 {
		return errf(CodeInvalidValue, field, "an %s public key is 32 bytes, got %d", alg, len(key))
	}
	return nil
}

// PairingConfirmation is what the phone posts back to finish pairing. It
// carries the phone's public key material, never a private key, and never the
// bearer token it is about to be issued.
type PairingConfirmation struct {
	Header
	DeviceID    string   `json:"device_id"`
	PairingCode string   `json:"pairing_code"`
	Label       string   `json:"label"`
	Platform    Platform `json:"platform"`
	PublicKey   string   `json:"public_key"`
	ConfirmedAt string   `json:"confirmed_at"`
}

// NewPairingConfirmation returns a confirmation with its envelope filled in.
func NewPairingConfirmation() PairingConfirmation {
	return PairingConfirmation{Header: newHeader(SchemaPairingOK)}
}

func (p *PairingConfirmation) SchemaName() string { return SchemaPairingOK }
func (p *PairingConfirmation) ByteLimit() int     { return MaxRequestBytes }

// Redacted returns a copy with the one-time code masked.
func (p PairingConfirmation) Redacted() PairingConfirmation {
	if p.PairingCode != "" {
		p.PairingCode = "[redacted]"
	}
	return p
}

func (p *PairingConfirmation) Validate() error {
	if err := p.validate(SchemaPairingOK); err != nil {
		return err
	}
	if err := validateID("device_id", PrefixDevice, p.DeviceID); err != nil {
		return err
	}
	if err := validateText("pairing_code", p.PairingCode, MaxIdempotencyKeyBytes, true); err != nil {
		return err
	}
	if err := validateText("label", p.Label, MaxLabelBytes, true); err != nil {
		return err
	}
	if err := inVocabulary("platform", string(p.Platform), "platform"); err != nil {
		return err
	}
	if err := validatePublicKey("public_key", p.PublicKey); err != nil {
		return err
	}
	return validateTimestamp("confirmed_at", p.ConfirmedAt)
}
